[dev]
  command = "npm run start"

[build]
  command = "AWS_LAMBDA_FUNCTION_NAME=trickpuppeteer npm run build"

[[redirects]]
  from = "/hire"
  to = "/work/hire"

[[redirects]]
  from = "/legal"
  to = "/about/legal"

[[redirects]]
  from = "/log"
  to = "/about/log"
